version: "3"
services:
  nginx:
    image: nginx:latest
    depends_on:
      - php
      - mysql
    ports:
        - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/:/var/www/html/
    networks:
      - internal

  php:
    #image: php:7.4-fpm
    build: ./docker/php
    expose:
      - '9000'
    volumes:
      - ./app/:/var/www/html/
    networks:
      - internal

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'robofinance'
      MYSQL_USER: 'robofinance'
      MYSQL_PASSWORD: '111Ghjcnjvjk222_!'
      MYSQL_ROOT_PASSWORD: '111Ghjcnjvjk333_!'
    expose:
      - '3306'
    ports:
      - '3306:3306'
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - internal

networks:
  internal:
